### ISSUE TITLE
[Bug]: Latest ProbeInterface broke SpikeGLXInterface

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/neuroconv#127]
### What happened?

https://github.com/catalystneuro/neuroconv/runs/8136438434?check_suite_focus=true

For now, pinning to previous version of ProbeInterface as upper bound.

@h-mayorquin You know the most about this, do you think you can fix it?

### Steps to Reproduce

```python
pytest tests/test_on_data/test_gin_ecephys.py
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.9

### Package Versions

Same as full requirements, latest of all. Also included in the log above.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Also FYI @alejoe91

**Comment by h-mayorquin** [comment]
This is generated from the changes here 
https://github.com/SpikeInterface/probeinterface/pull/117

Which broke backwards compatibility on the output annotations of the function `read_spikgelx` here:
https://github.com/SpikeInterface/probeinterface/blob/97d93bfdd5127d278cbb8ca50330fa404200e6be/probeinterface/io.py#L933

(As it now uses `read_imro_string`) 

This causes the error because spikeinterface still assumes the previous probe interface annotations here:
https://github.com/SpikeInterface/spikeinterface/blob/80af883d539b3f3b953f9186842099effba12498/spikeinterface/extractors/neoextractors/spikeglx.py#L76

A simple fix would be to use "probe_type` as a key in `spikeinterface` instead of "imDatPrb_type".

I think this is an `spikeinterface` issue though, I will open another one there @alejoe91 @samuelgarcia 

For us, I don't know what else this breaks as I extract some information from the probes. I am checking that now.

**Comment by h-mayorquin** [comment]
This is already on the way of being addressed with the latest release. When they do this I can see if this generate any problems with the interface and then we can close this if it does not.

**Comment by weiglszonja** [comment]
@h-mayorquin I'm also seeing this error ```imDatPrb_type = probe.annotations["imDatPrb_type"]
KeyError: 'imDatPrb_type'``` when trying to convert ephys data for Fee lab. Is this issue fixed for you?

**Comment by weiglszonja** [comment]
@CodyCBakerPhD Installing `spikeinterface` from source fixed the issue for me, is it safe to update the version number for `spikeinterface` in the requirements? Currently it is:
https://github.com/catalystneuro/neuroconv/blob/49cc85fc20568e52101096d4d1a14b815cf0754e/src/neuroconv/datainterfaces/ecephys/requirements.txt#L2
I'm not sure which version it is pinned to, before I updated it, this would show up for me as:  `spikeinterface` is `0.94.0`, `spikeextractors` is `0.9.10`.
Now I have `spikeinterface` `0.95.1`

**Comment by CodyCBakerPhD** [comment]
@weiglszonja So, you're saying latest release of SI resolves the issue? If so can you open a PR to fix this issue by simply updating the requirements?

**Comment by weiglszonja** [comment]
@CodyCBakerPhD yes it works for me, the issue in `spikeinterface` that @h-mayorquin linked has already been closed as completed, so I guess it resolved for him as well since then.

**Comment by h-mayorquin** [comment]
Yes, this should be resolved now with the latest release. I am gonna check if bumping spikeinterface version does not cause other errors now.
