### ISSUE TITLE
[Feature]: parsing numpydoc

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#278]
### What would you like to see added to NeuroConv?

We have many docstrings over the repo that repeat themselves multiple times. Each time we type it fresh in a new function, we run the risk of adding typos and other differences. Each time we copy/paste it we run the risk of propagating tiny differences that existed from the copy source. If we ever need to adjust some small part of the docstring, we have to remember to propagate that change everywhere.

This becomes an annoyance.
@CodyCBakerPhD has already proposed to potential approaches: #273 and #274

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by bendichter** [comment]
I like #274 , but what about this slight modification:

I like this idea. 

What about this slight modification:

```python
import from . import func1

def func2(arg1):
    """"
    {func1.arg1}
    """"
    func1(arg1)
```

1. The original func1 docstring stays intact
2. The only import needed is the func1 import we already do
3. The docstring reference is more specific

One advantage is we could use this approach for other libraries too, as long as they use strict Numpy formatting. I think we can convince Alessio and Samuel to do that for spikeinterface.

**Comment by bendichter** [comment]
I also think we should have a `@dynamic_docstring` decorator that automatically resolves these

**Comment by h-mayorquin** [comment]
They do some minor version of this for spikeinterface (@alejoe91):
https://github.com/SpikeInterface/spikeinterface/blob/master/spikeinterface/core/waveform_extractor.py#L1252

In their case, it is for the parallelization arguments which are repeated across the whole repo:
https://github.com/SpikeInterface/spikeinterface/blob/bebf203ae5ddc2936d3ff56d36ecacc9a2aafac6/spikeinterface/core/job_tools.py#L18-L35

I took a quick look at how matplotlib handles this. They have a lot of styling parameters which are repeated across every possible function so in their case the problem is even more exacerbated. Turns out, they have adopted a string interpolation whose interface is a decorate of the kind we are suggesting here. Take a look at their description of the problem:

https://matplotlib.org/stable/devel/documenting_mpl.html#keyword-arguments

However, look at the discalimer at the beginning of the link above. The developers don't seem to be totally comfortable with the current string interpolation solution. You can see some of the discussion in the following link which echoes some of the points we have made alread on #273 and #274 plus some other concerns:

https://github.com/matplotlib/matplotlib/issues/9414

Also, I also checked scikit-learn. They manage have parameters, such as `n_jobs` for parallelization, which appear on most predictors and I wanted to see how they keep that synchronized across them. A shallow and quick exploration of their code base seem to indicate that they just went the hard way themselves, that is, they just write the identical docstring everywhere. 

Just some points and references that I thought would be useful for the discussion.

**Comment by bendichter** [comment]
Thanks for the pointers, @h-mayorquin! It is indeed interesting to see the very same debate in another community.

**Comment by bendichter** [comment]
I think these points nicely summarize the conflicting priorities:

> 1. Generate docstrings that are as helpful to the user as possible, regardless of the method used to view them: directly in the source code, in an interactive ipython session, e.g. using the trailing question mark, and in the online sphinx-generated docs.
> 2. Avoid making our codebase more complex and convoluted than it already is.
> 3. Related to (2), make it as easy as possible to improve the documentation.
> 4. Observe the DRY principle when possible.

**Comment by CodyCBakerPhD** [comment]
> I think these points nicely summarize the conflicting priorities:

Specifically,

the feature of dynamic docstrings conflicts with (1) since it only applies to a subset of those viewing possibilities, and (2) by making docstrings complex...

...but static docstrings conflicts with (3) since without them it is difficult to ensure a docstring improvement is propagated everywhere to which it applies, and (4) since it violates DRY.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin what do you think of the Config option proposed by @weiglszonja at the end of the first post in #280? I really think it could alleviate the central source of this issue.

We'd still have repetition for arguments like `nwbfile`/`nwbfile_path` (whichare the same everywhere) but at least the ones being repeated would be really simple, like the sci-kit learn docstrings (a couple sentences at most). The more detailed arguments that need rich explanation in docstrings would be written only once in a Config class.

**Comment by CodyCBakerPhD** [comment]
Team unanimously agreed that dynamic docstrings are not a good way to go, but adding tests where easily applicable could be beneficial

Replaced by #284
