### ISSUE TITLE
[Bug]: Mocks should not inherit from classses

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#299]
### What happened?

This line:

https://github.com/catalystneuro/neuroconv/blob/a872ae5885d672dc72c3eb48c6c6c88ef137e9ab/src/neuroconv/tools/testing/mock_interfaces.py#L10

is problematic because we are not calling the `super()__init__` in the init. This is causing problems as I am trying to push features upstream into `BaseRecordingInterface`. I was making the assumption that all children of that class call the class `__init__`, which is an assumption I should be able to make as this is best practice for OOP in Python. 

### Steps to Reproduce

Mocks really shouldn't me children of the classes they mock. See how I built mocks in PyNWB, e.g. here: 

https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/src/pynwb/testing/mock/behavior.py

this is a better way to build mocks because it doesn't violate OOP best practices.

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.7

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
> this is a better way to build mocks because it doesn't violate OOP best practices.

You can do that in PyNWB because the signatures and `__init__` behavior are the same except for different defaults

Here, we need the `MockSpikeGLXNIDQInterface` to behave in every way like a normal `SpikeGLXNIDQInterface` after initialization, but we don't have an actual `.nidq.bin` file so we synthesize the recording extractor in-memory

Which means the `__init__` signatures don't match between the mock and the actual

What other way would you recommend around this?

I'd just say add `es_key` to the `__init__` of https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/tools/testing/mock_interfaces.py#L14 and then set `self.es_key = es_key` to mimic what the non-mock would do at that step

**Comment by bendichter** [comment]
> You can do that in PyNWB because the signatures and __init__ behavior are the same except for different defaults

I don't see why that would prevent you from using the same strategy here.

> Here, we need the MockSpikeGLXNIDQInterface to behave in every way like a normal SpikeGLXNIDQInterface after initialization

I don't see why the other approach would be a problem for this.

**Comment by bendichter** [comment]
oh, now I get it. You can't initialize because you don't have an actual file. Hmm.
