### ISSUE TITLE
[Bug]: YAML data_interfaces should be a dict, not a list

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#304]
### What happened?

Right now we in the conversion YAML format we have:

```yaml
data_interfaces:
  - SpikeGLXRecordingInterface
  - PhySortingInterface
```

but what if you want to include more than one SpikeGLXRecordingInterface? When specifying the inputs, how can you know which input is going to which interface? To solve this, we need to name the interfaces, similarly to how we specify the `NWBConverter` class. The names can be anything but must be unique amongst each other:

```yaml
data_interfaces:
  ap0: SpikeGLXRecordingInterface
  spike_sorting: PhySortingInterface
```

@CodyCBakerPhD, what do you think?

### Steps to Reproduce

```python
n.a.
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.7

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Ah, yes. Currently assumes only one instance of each interface. In particular, the `source_data` level at each `session` would not allow multiple keys of the same interface type (even if different inputs) https://github.com/catalystneuro/neuroconv/blob/main/tests/test_on_data/conversion_specifications/GIN_conversion_specification.yml#L18-L20 because the interface name is the key

This should be easy to fix as you suggest

**Comment by CodyCBakerPhD** [comment]
Also similar in spirit to #269
