### ISSUE TITLE
[Bug]:  zero-dimensional arrays cannot be concatenated

### ISSUE THREAD

**Issue by vncntprvst** [catalystneuro/neuroconv#529]
### What happened?

I'm adding a single video file with timestamps to a NWB file. 
The code seems to assume that there will be multiple videos appended. 

### Steps to Reproduce

```python
This is the code I run:

import os
video_file = os.path.relpath(f"{projectDir + subjectDir + sessionDir}sc099_1217_1800_20211217-183100_HSCam.avi")

# Add the video as external file using class VideoInterface and the video frame timestamps loaded from the TTL data
from neuroconv.datainterfaces import VideoInterface
video_data = VideoInterface(file_paths=[video_file])
video_data.set_aligned_timestamps(ttlSeries.timestamps)

video_data.add_to_nwbfile(nwbfile=nwbfile)
```
```


### Traceback

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[29], line 13
     10 video_data = VideoInterface(file_paths=[video_file])
     11 video_data.set_aligned_timestamps(ttlSeries.timestamps)
---> 13 video_data.add_to_nwbfile(nwbfile=nwbfile)

File ~/mambaforge/envs/wanglabnwb/lib/python3.9/site-packages/neuroconv/datainterfaces/behavior/video/videodatainterface.py:340, in VideoInterface.add_to_nwbfile(self, nwbfile, metadata, stub_test, external_mode, starting_frames, chunk_data, module_name, module_description, compression, compression_options)
    338     image_series_kwargs.update(starting_time=starting_time, rate=rate)
    339 elif timing_type == "timestamps":
--> 340     image_series_kwargs.update(timestamps=np.concatenate(self._timestamps))
    341 else:
    342     raise ValueError(f"Unrecognized timing_type: {timing_type}")

ValueError: zero-dimensional arrays cannot be concatenated
```

### Operating System

Windows

### Python Executable

Conda

### Python Version

3.9

### Package Versions

[environment_for_issue.txt](https://github.com/catalystneuro/neuroconv/files/12166077/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by vncntprvst** [comment]
This was fixed by making the timestamps a list as below:
```
video_data.set_aligned_timestamps([ttlSeries.timestamps])
```

**Comment by CodyCBakerPhD** [comment]
Thanks @vncntprvst for raising the issue so that others can be directed to the solution if they ever encounter it in the future!

Indeed, because the `VideoInterface` works off of `file_paths: List[FilePath]` logic, the alignment methods are also based off of list-wrapped values for each entry in `file_paths`.

I appreciate this can seem awkward when there is only one file that needs to be converted - I wonder if it might be better to split the current interface in a number of ways as I mentioned originally in #403 - separate interfaces for internal vs. external mode - and now perhaps separate modes for a single path as opposed to multiple ordered paths

Any thoughts on the last part @h-mayorquin?

**Comment by h-mayorquin** [comment]
I think that makes sense. I feel it will make the code in the interface clearer.

**Comment by CodyCBakerPhD** [comment]
Ideas for improvement essentially absorbed into #182
