### ISSUE TITLE
[Documentation]: Should remark that test data is required for running the tests.

### ISSUE THREAD

**Issue by magland** [catalystneuro/neuroconv#643]
### What would you like changed or added to the documentation and why?

This page says to run tests simply by pip installing and running `pytest`

https://neuroconv.readthedocs.io/en/main/developer_guide/testing_suite.html

However, this doesn't work since the test data needs to be downloaded. I only discovered that by scrolling down to the bottom of the page. I think this should be noted at the top.

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
By 'doesn't work' do you mean it actually errors out? Or that it runs all tests, but a portion of them fail because of missing data?

**Comment by CodyCBakerPhD** [comment]
I.e., 'running tests' does not mean 'passing all tests'

**Comment by CodyCBakerPhD** [comment]
> I mean that the tests ran, but some failed due to missing data.

OK, so what kind of documentation would you expect under that section?

Feel free to submit a PR with your suggestion

From my perspective, what we have now is simple and truthful to use a quick reference, with the following sections going into greater depth for anyone that is curious why certain outcomes occurred

**Comment by h-mayorquin** [comment]
> > I.e., 'running tests' does not mean 'passing all tests'
> 
> Yes I misspoke. I mean that the tests ran, but some failed due to missing data.

Which ones? I think that the tests should pass if you don't have the data, a skip warning as pytest does.

**Comment by magland** [comment]
> > > I.e., 'running tests' does not mean 'passing all tests'
> > 
> > 
> > Yes I misspoke. I mean that the tests ran, but some failed due to missing data.
> 
> Which ones? I think that the tests should pass if you don't have the data, a skip warning as pytest does.

@h-mayorquin The very first one fails for example

```
pytest docs/conversion_examples_gallery/behavior/audio.rst
->
No such file or directory: '/home/magland/src/neuroconv/behavior_testing_data/audio/natural_audio_recording.wav'
```

I think all that would be needed is in the first paragraph to say something like: "Please note that some of these tests are expected to fail until you have downloaded the test data as described below."

**Comment by h-mayorquin** [comment]
Thanks, yeah as Cody was saying, they should be skipped if the data is not available. We will take a look.

The thing is though, that if you have some of data but not all the tests do fail. I am not sure if that's the case here. Say you have some of the data for the recording / spikeinterface  /ecephys test but you are missing some format. Then all your tests would fail. 

Could that be your case? Do you have some of the behavior data but not all of them? (this happens to me in my system because I have not downloaded the latest data for the ophys tests).

**Comment by magland** [comment]
Yes, I have the ephy_testing_data.

And now I am realizing I was probably manually targeting particular tests that should have been skipped. So maybe everything is working as intended. Still, I think it would be nice to have some sort of statement at the top saying that the tests that require testing data will be skipped.

**Comment by h-mayorquin** [comment]
Do you have the behavior data folder?

That seems to be the one causing the trouble. If you have some of the data but not file then it will be fail. Right now then skip is based on the folder if I remember well, maybe we could make it per file.

Yes, I think there is no cost in adding a small warning. In my view we should add that and make more specific skips a todo in the backlog.

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin Can you point me to this folder based skipping you've mentioned? I do not recall this being present in our setup

And a big point against skipping automatically is that case from a couple years back when the testing suite had been failing silently for a month due to a cache issue and had not caught bugs that had popped up because it was skipping the tests that would have caught them

Since then, it has been preferred to 'run all and fail some' if something isn't configured right

Added a note about expected behavior in #652

**Comment by h-mayorquin** [comment]
My memory failed me indeed. There is no such a thing. I wonder where I got this.

If we wanted we could make the tests fail in the CI but pass locally when the datasets are not available.

**Comment by h-mayorquin** [comment]
That seems convicing to me, @CodyCBakerPhD . There is not a lot to win other than convenience for a limited set of users and might introduce silent failings plus the developer effort. Fair enough.
