### ISSUE TITLE
[Feature]: allow user to force storing timestamps (as opposed to start time + rate) for BaseRecordingExtractorInterface subclasses

### ISSUE THREAD

**Issue by johnmbarrett** [catalystneuro/neuroconv#712]
### What would you like to see added to NeuroConv?

When writing ephys data to NWB using neuroconv, I would like to be able to explicitly control whether the timestamps are sorted as a vector, or a simple rate & start time.

Right now, `BaseRecordingExtractorInterface.add_to_nwbfile` via `neuroconv.tools.spikeinterface.add_electrical_series` decides whether to store timings for a recording as an explicit timestamp vector or a starting time & rate based on the regularity of the timestamps (i.e. are they identical to within 6 decimal places). This can introduce timing drift in certain scenarios. Unless I'm missing something, the user has no control over this behaviour.

As far as I can tell by inspecting the code, there is no trivial way to override this behaviour by subclassing whichever data interface you're working with. It's not possible to add timestamps to the ElectricalSeries once it's added to the NWB file. The only option would be to reimplement `BaseRecordingExtractorInterface.add_to_nwbfile`, which would be a huge amount of code duplication.

### Is your feature request related to a problem?

This is related to https://github.com/catalystneuro/neuroconv/issues/302 and https://github.com/catalystneuro/neuroconv/issues/711. I have two systems (one Neuropixels, one Intan) with similar but not identical sampling rate. I can align them using a TTL pulse train sent from one system to the other, but the aforementioned regularity check means that only the aligned starting time and original sampling rate are saved to the NWB file. The precise, per-sample alignment is lost. There is non-trivial drift between the aligned timestamps and those inferred from the sampling rate: about 0.5 ms/min. For my current purposes that's not catastrophic, but for longer recordings (tens of minutes) it's not hard to imagine experiments where that kind of timing drift could meaningfully affect the results. 

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
@johnmbarrett Thanks for the clear and concise request!

I have advocated for exactly this behavior in the past, but others on the team have preferred to 'let NeuroConv make the data engineering decisions for the users', which it can still do by default but at least this exposes control over the behavior to let advanced users such as yourself to decide how they want data to be written

I've opened #713 in draft to enable this

**Comment by johnmbarrett** [comment]
Once again, no worries and thanks for your quick attention! Checked out your changes and other than a missing pass through of the `use_timestamps` argument from `add_recording` to `add_electrical_series` around line 777 of spikeinterface.py, it all seems to work fine and I end up with an NWB file with the correct timestamps. Thanks for your help!

**Comment by h-mayorquin** [comment]
Hi,

@CodyCBakerPhD 
> I have advocated for exactly this behavior in the past, but others on the team have preferred to 'let NeuroConv make the data engineering decisions for the users', which it can still do by default but at least this exposes control over the behavior to let advanced users such as yourself to decide how they want data to be written

I think we decided to do exactly this on the last December meeting? Follow best practices by default but expose an option to allow users to do this if they want.

With that said, I think we should attempt that @johnmbarrett case to be solved by the default case. That is, if the timestamps have an irregularity that will lead to a drift of milliseconds per hour then we should not consider them regular. Can we fix that by changing the number of significan digits in our check? We can transform to milliseconds and compare.

**Comment by CodyCBakerPhD** [comment]
> Can we fix that by changing the number of significan digits in our check? We can transform to milliseconds and compare.

I think it would be a change to the nature of the check, which right now is an assertion on the resolution of the first order difference; how small that happens to need to be to prevent accumulation of drift over an arbitrary time interval is pretty subjective. In fact, similar to the IBL problem, we _could_ think of them as being regular, but that extra delta that goes onto the baseline rate is sensitive over longer periods of time

In the end, it takes work to properly resolve all of these issues for a particular rig; so if someone took the time to set their own timestamps on an extractor, that's significant and should be respected at all times; the bigger issue is that I think some extractors used to just generate timestamps on the fly by taking an `arange` over their rate, which caused our distrust in this originally

So @h-mayorquin if you could check on the SI/neo side of things that no extractor generates artificial timestamps anymore (in the sense that `has_time_vector` would be false after `__init__` unless the format truly handles it inherently, like that one neuralynx type and maybe a couple others) then we could go back to relying on that instead of making assumptions about the data which might cause problems for users

**Comment by CodyCBakerPhD** [comment]
Another situation where we set timestamps and a potentially incorrect rate was inferred over a long period of time: https://github.com/catalystneuro/jazayeri-lab-to-nwb/blob/da0c4fd9c18983adf79c967dbb8114e4045b2092/src/jazayeri_lab_to_nwb/watters/nwb_converter.py#L146

**Comment by h-mayorquin** [comment]
Hi @johnmbarrett we finally implemented this.

We are also planning adding better heuristics so the default (timestamps -> rate) decision works better.
