### ISSUE TITLE
[Bug]: rmv WaveformExtractor

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/neuroconv#772]
### What happened?

The latest version of spikeinterface has removed `WaveformExtractor`, which is now causing an import error for the dev installation. See https://github.com/catalystneuro/neuroconv/actions/runs/8225815354/job/22491395514?pr=771

Let's look at refactoring NeuroConv to match so that we can benefit from the latest SpikeInterface features.

@h-mayorquin , you might be a good person to handle this.

### Steps to Reproduce

```python
See above
```

### Operating System

Linux

### Python Executable

Conda

### Python Version

3.8

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
Already on the radar from https://github.com/catalystneuro/neuroconv/pull/768#issuecomment-1981525510

One question might be how smoothly we want to remove it; some current pipelines (as I recall, the ones Alessio setup for Allen Insistute?) might depend on it otherwise and we wouldn't want to break them

Perhaps `if hasattr(spikeinterface, WaveformExtractor)` then define write methods as we do now, otherwise don't define until we add support for the SortingAnalyzer?

**Comment by h-mayorquin** [comment]
All right, I will take a look.

Some context for provenance:
* The `SortyingAnalyser` that will replace `WaveformExtractor` is now on dev and according to @alejoe91 in Slack it will be released on May. 
* Other relevant issue here:
https://github.com/SpikeInterface/spikeinterface/pull/2546

**Comment by CodyCBakerPhD** [comment]
This has since been resolved I believe, right @h-mayorquin?

**Comment by h-mayorquin** [comment]
This is done.
