### ISSUE TITLE
[Feature]: Add support for multiple different timestamps in BaseTemporalAlignmentInterface

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/neuroconv#921]
### What would you like to see added to NeuroConv?

Some interfaces have multiple different timestamps that need to be aligned such as the MedPCInterface #883 and the TDTFiberPhotometryInterface #920.  But the timestamp methods are currently set up to manage a single array of timestamps.  Instead, we should have some kind of dictionary of aligned timestamps mapped to a name.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/catalystneuro/neuroconv/blob/main/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/catalystneuro/neuroconv/issues)?

**Comment by CodyCBakerPhD** [comment]
What are the different streams of the TDT interface?

Can you think of more examples?

If it's only for a handful of very special cases I'd be against adding the complexity to the base class

**Comment by pauladkisson** [comment]
For TDT, there is one set of timestamps for the response series's and another for the commanded voltages.

**Comment by pauladkisson** [comment]
One might need it for ecephys for the raw voltage recording + spike times. Any behavioral interface with multiple streams of behavior would need it (position and rear times for example). To me, it seems like a pretty general use case.

**Comment by CodyCBakerPhD** [comment]
> One might need it for ecephys for the raw voltage recording + spike times.

Those are separate interfaces; `Recording` vs. `Sorting` - also these would share the same time basis since the spiking is derived from the recording



> Any behavioral interface with multiple streams of behavior would need it (position and rear times for example).

Separate camera devices would use separate copies of the same interface for the raw Video as well as pose estimation (the very schematic design of `ndx-pose`, especially the newer training classes, is not intended to mix camera streams unless you've triangulated, which would itself only have a single time stream)



> If ophys ever adds commanded voltages, it would need it. 

Well, general ophys data has never seen it, so if it someone ever does occur it would probably be through a separate interfaces (such as an auxiliary interface for whatever voltage system they used)

So far sounds specific to Fibre Photometry, so I'd recommend just doing what you need to for that interface
